### ISSUE TITLE
Final report script file

### ISSUE THREAD

**Issue by ray2g** [labBioinfo/workflow#22]
Using the packages ggpubr and microbiome, we need to develop a final script to report all the taxonomy, statistical, metagenomic and phylogenetic information from the samples intuitively, having plots easy to understand and an interactive menu where we choose the taxonomic class to analyze.

**Comment by ray2g** [comment]
for plot phylogenetic trees : (ggtree) https://www.molecularecologist.com/2017/02/phylogenetic-trees-in-r-using-ggtree/

**Comment by ray2g** [comment]
for plot phylogenetic trees : (ggtree) https://www.molecularecologist.com/2017/02/phylogenetic-trees-in-r-using-ggtree/

**Comment by AxisKriel** [comment]
I think being able to generate a report that encompasses all the segments of analysis that are possible with this program is a great idea. It would allow us to output more consistent data about a specific sample.
