### ISSUE TITLE
Report guy need the list for " What gonna be reported?" :/

### ISSUE THREAD

**Issue by ray2g** [labBioinfo/workflow#3]
Gimme your opinion for what we must report. :nerd_face: 

-project info
-Sample info
-plots

welp me :cry:

**Comment by smokewheateveryday** [comment]
The current workflow should be able to create a MongoDB database and download some of the files you'll be analyzing. Consider running the workflow and downloading a few of the database's files (you can use CTRL+C to stop the downloads). You can get ideas from there.

**Comment by AxisKriel** [comment]
Is this done yet? If it is, it can be closed.
